# Generated by Django 4.2.2 on 2023-08-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_subscriptioncourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='стоимость курса'),
        ),
        migrations.AddField(
            model_name='payments',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EURO')], default='usd', verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(blank=True, null=True, verbose_name='статус платежа'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_id',
            field=models.CharField(blank=True, null=True, verbose_name='id платежа в stripe'),
        ),
    ]
