# Generated by Django 4.2.2 on 2023-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_price_payments_currency_payments_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='обновлен'),
        ),
    ]
